language: python

python:
  - 3.5
 
notifications:
  email: false
  
sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev
      - python-lxml
      - python-simplejson
      - python-serial
      
env:
  global:
  - VERSION="11.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"

  matrix:
  - TESTS="1" ODOO_REPO="odoo/odoo"

before_install:
  - sudo apt-get install -y unoconv libav-tools ghostscript imagemagick
  - sudo cp /usr/lib/python2.7/dist-packages/uno* ~/.virtualenv/python3.5.5/lib/python3.5/site-packages/
  - pip3 install moviepy Wand

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly

script:
  - travis_run_tests

after_success:
  - travis_after_tests_success
